/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrendSlugRouteImport } from './routes/trend.$slug'
import { Route as SupplementSlugRouteImport } from './routes/supplement.$slug'
import { Route as SectionSectionRouteImport } from './routes/section.$section'
import { Route as AuthorSlugRouteImport } from './routes/author.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as ApiVoiceTtsRouteImport } from './routes/api/voice.tts'
import { Route as ApiVoiceSttRouteImport } from './routes/api/voice.stt'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrendSlugRoute = TrendSlugRouteImport.update({
  id: '/trend/$slug',
  path: '/trend/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementSlugRoute = SupplementSlugRouteImport.update({
  id: '/supplement/$slug',
  path: '/supplement/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSectionRoute = SectionSectionRouteImport.update({
  id: '/section/$section',
  path: '/section/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorSlugRoute = AuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiVoiceTtsRoute = ApiVoiceTtsRouteImport.update({
  id: '/api/voice/tts',
  path: '/api/voice/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSttRoute = ApiVoiceSttRouteImport.update({
  id: '/api/voice/stt',
  path: '/api/voice/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/authors': typeof AuthorsRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/video': typeof VideoRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/section/$section': typeof SectionSectionRoute
  '/supplement/$slug': typeof SupplementSlugRoute
  '/trend/$slug': typeof TrendSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/authors': typeof AuthorsRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/video': typeof VideoRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/section/$section': typeof SectionSectionRoute
  '/supplement/$slug': typeof SupplementSlugRoute
  '/trend/$slug': typeof TrendSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/authors': typeof AuthorsRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/video': typeof VideoRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/section/$section': typeof SectionSectionRoute
  '/supplement/$slug': typeof SupplementSlugRoute
  '/trend/$slug': typeof TrendSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/authors'
    | '/bookmarks'
    | '/contact'
    | '/gallery'
    | '/live'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/video'
    | '/admin/ads'
    | '/admin/profile'
    | '/admin/users'
    | '/api/chat'
    | '/article/$slug'
    | '/author/$slug'
    | '/section/$section'
    | '/supplement/$slug'
    | '/trend/$slug'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/api/voice/stt'
    | '/api/voice/tts'
    | '/admin/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/authors'
    | '/bookmarks'
    | '/contact'
    | '/gallery'
    | '/live'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/video'
    | '/admin/ads'
    | '/admin/profile'
    | '/admin/users'
    | '/api/chat'
    | '/article/$slug'
    | '/author/$slug'
    | '/section/$section'
    | '/supplement/$slug'
    | '/trend/$slug'
    | '/admin'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/api/voice/stt'
    | '/api/voice/tts'
    | '/admin/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/authors'
    | '/bookmarks'
    | '/contact'
    | '/gallery'
    | '/live'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/update-password'
    | '/video'
    | '/admin/ads'
    | '/admin/profile'
    | '/admin/users'
    | '/api/chat'
    | '/article/$slug'
    | '/author/$slug'
    | '/section/$section'
    | '/supplement/$slug'
    | '/trend/$slug'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/api/voice/stt'
    | '/api/voice/tts'
    | '/admin/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  AuthorsRoute: typeof AuthorsRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  VideoRoute: typeof VideoRoute
  ApiChatRoute: typeof ApiChatRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  AuthorSlugRoute: typeof AuthorSlugRoute
  SectionSectionRoute: typeof SectionSectionRoute
  SupplementSlugRoute: typeof SupplementSlugRoute
  TrendSlugRoute: typeof TrendSlugRoute
  ApiVoiceSttRoute: typeof ApiVoiceSttRoute
  ApiVoiceTtsRoute: typeof ApiVoiceTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trend/$slug': {
      id: '/trend/$slug'
      path: '/trend/$slug'
      fullPath: '/trend/$slug'
      preLoaderRoute: typeof TrendSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplement/$slug': {
      id: '/supplement/$slug'
      path: '/supplement/$slug'
      fullPath: '/supplement/$slug'
      preLoaderRoute: typeof SupplementSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$section': {
      id: '/section/$section'
      path: '/section/$section'
      fullPath: '/section/$section'
      preLoaderRoute: typeof SectionSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$slug': {
      id: '/author/$slug'
      path: '/author/$slug'
      fullPath: '/author/$slug'
      preLoaderRoute: typeof AuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/voice/tts': {
      id: '/api/voice/tts'
      path: '/api/voice/tts'
      fullPath: '/api/voice/tts'
      preLoaderRoute: typeof ApiVoiceTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/stt': {
      id: '/api/voice/stt'
      path: '/api/voice/stt'
      fullPath: '/api/voice/stt'
      preLoaderRoute: typeof ApiVoiceSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  AuthorsRoute: AuthorsRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  VideoRoute: VideoRoute,
  ApiChatRoute: ApiChatRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  AuthorSlugRoute: AuthorSlugRoute,
  SectionSectionRoute: SectionSectionRoute,
  SupplementSlugRoute: SupplementSlugRoute,
  TrendSlugRoute: TrendSlugRoute,
  ApiVoiceSttRoute: ApiVoiceSttRoute,
  ApiVoiceTtsRoute: ApiVoiceTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
